version: '1'

services:

  proxy:
    container_name: proxy
    build:
      context: ./nginx
    depends_on:
      - app
    ports: 
      - '8080:80'
    networks:
      - app-network

  app:
    container_name: app
    build:
      context: ./node
    #Ativando a linha abaixo, o retorno é sempre 502. O contêiner não fica rodando o "node index.js".
    #entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    tty: true
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    build:
      context: ./mysql
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
